# Generated by Django 6.1.1 on 2026-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=30, verbose_name='Codigo do produto')),
                ('nome_produto', models.CharField(max_length=120, verbose_name='Nome do produto')),
                ('marketplace', models.CharField(choices=[('Mercado Livre', 'Mercado Livre'), ('Shopee', 'Shopee'), ('Magazine Luiza', 'Magazine Luiza'), ('Casas Bahia', 'Casas Bahia'), ('Shein', 'Shein'), ('Leroy Merlin', 'Leroy Merlin'), ('Madeira Madeira', 'Madeira Madeira'), ('Outro', 'Outro')], max_length=40, verbose_name='Marketplace')),
                ('motivo', models.CharField(choices=[('Produto avariado', 'Produto avariado'), ('Produto errado', 'Produto errado'), ('Desistencia do cliente', 'Desistencia do cliente'), ('Peca faltando', 'Peca faltando'), ('Atraso na entrega', 'Atraso na entrega'), ('Outro', 'Outro')], max_length=40, verbose_name='Motivo da devolucao')),
                ('situacao', models.CharField(choices=[('Aguardando avaliacao', 'Aguardando avaliacao'), ('Revenda', 'Revenda'), ('Descarte', 'Descarte')], default='Aguardando avaliacao', max_length=40, verbose_name='Situacao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do produto (R$)')),
                ('data_devolucao', models.DateField(verbose_name='Data da devolucao')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
