# Generated by Django 6.1.1 on 2026-09-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='registrado_por',
            field=models.CharField(blank=True, max_length=60, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='codigo_produto',
            field=models.CharField(choices=[('Kit10InfantilRosa', 'Kit10InfantilRosa - Kit 10 Cabides Infantis de Veludo Rosa'), ('Plastificadora110v', 'Plastificadora110v - Plastificadora Poliseladora 110v'), ('Jogo4PanelasBege', 'Jogo4PanelasBege - Jogo de 4 Panelas Beges Para Fogão de Indução'), ('Bike120kg', 'Bike120kg - Bicicleta Ergométrica Pequena Portátil Até 120kg'), ('Lixeira40L', 'Lixeira40L - Lixeira de Alumínio 40L Com Pedal'), ('InfladorAzul220vMedidor', 'InfladorAzul220vMedidor - Inflador de Balão Azul 220v com Medidor de MDF'), ('CercadinhoAmarelo', 'CercadinhoAmarelo - Cercadinho Amarelo para Bebês'), ('Paint110v', 'Paint110v - Paint Pistola de Pintura 110v com Alça'), ('VaralPortátil', 'VaralPortátil - Varal Portátil com 3 Andares Para Apartamento'), ('Kit50CabidePreto', 'Kit50CabidePreto - Kit 50 Cabides Tamanho 45cm de Veludo Preto'), ('EscorredorPequeno', 'EscorredorPequeno - Escorredor de Louças Pequeno 50cm 2 Andares'), ('VasoCD19', 'VasoCD19 - Vaso de Polietileno Vermelho 65cm Sem Prato'), ('LixeiraFralda', 'LixeiraFralda - Lixeira Para Fralda Infantil Rosa')], max_length=30, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='marketplace',
            field=models.CharField(choices=[('Mercado Livre', 'Mercado Livre'), ('Shopee', 'Shopee'), ('Magazine Luiza', 'Magazine Luiza'), ('Casas Bahia', 'Casas Bahia'), ('Shein', 'Shein'), ('Leroy Merlin', 'Leroy Merlin'), ('Madeira Madeira', 'Madeira Madeira'), ('Tiktok Shop', 'Tiktok Shop'), ('Outro', 'Outro')], max_length=40, verbose_name='Marketplace'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='motivo',
            field=models.CharField(choices=[('Produto avariado', 'Produto avariado'), ('Produto errado', 'Produto errado'), ('Desistencia do cliente', 'Desistência do cliente'), ('Peca faltando', 'Peça faltando'), ('Atraso na entrega', 'Atraso na entrega'), ('Outro', 'Outro')], max_length=40, verbose_name='Motivo da devolucao'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='situacao',
            field=models.CharField(choices=[('Aguardando avaliação', 'Aguardando avaliação'), ('Revenda', 'Revenda'), ('Descarte', 'Descarte')], default='Aguardando avaliacao', max_length=40, verbose_name='Situacao'),
        ),
    ]
